# Site settings
title: moad
email: music@moad.info
description: 3 guys, plenty of instruments and a few PCs, moving between experimental indie and electronic rock
baseurl: "/moad-site" # /moad-site
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
facebook_username: moad.band
youtube_username: moad videos
soundcloud_username: moad_music


# Build settings
markdown: kramdown
exclude: [/node_modules]

# Collections

# http://stackoverflow.com/questions/16316311/github-pages-and-relative-paths
